[build]
publish = "public"
ignore = "(exit 1)"

[[plugins]]
package = "../"
  [plugins.inputs]
  
  # The base url of your site (optional, default = main URL set in Netlify)
  baseUrl = "example.com"

  # Path to the sitemap URL (optional, default = /sitemap.xml)
  sitemapPath = "/sitemap.xml"

  # Time in seconds to not submit the sitemap after successful submission
  ignorePeriod = 600
  
  # Enabled providers to submit sitemap to (optional, default = 'google', 'bing'). Possible providers are currently only 'google' and 'bing'.
  providers = [
    "google",
    "bing",
    "yandex"
  ]

[[plugins]]
package = "@netlify/plugin-local-install-core"
